-- GreenPasture MIS - Phase 1 database schema
-- Explicit DDL for the two Phase-1 entities (Section 9.1 of the proposal): Cattle and MilkProduction.
-- Hibernate (hbm2ddl.auto=update) can generate this schema automatically on startup;
-- this script is provided so the database can also be created independently of the app.

CREATE TABLE IF NOT EXISTS cattle (
    cattle_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag_number      VARCHAR(20)  NOT NULL UNIQUE
                        CHECK (tag_number ~ '^[A-Za-z0-9-]{3,20}$'),
    breed           VARCHAR(255) NOT NULL,
    date_of_birth   DATE         NOT NULL
                        CHECK (date_of_birth <= CURRENT_DATE),
    health_status   VARCHAR(50)  NOT NULL
                        CHECK (health_status IN ('Healthy', 'Under observation', 'Under treatment'))
);

CREATE TABLE IF NOT EXISTS milk_production (
    production_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cattle_id       BIGINT           NOT NULL
                        REFERENCES cattle (cattle_id) ON DELETE CASCADE,
    record_date     DATE             NOT NULL
                        CHECK (record_date <= CURRENT_DATE),
    shift           VARCHAR(10)      NOT NULL
                        CHECK (shift IN ('Morning', 'Evening')),
    quantity_liters DOUBLE PRECISION NOT NULL
                        CHECK (quantity_liters >= 0 AND quantity_liters <= 100)
);

CREATE INDEX IF NOT EXISTS idx_milk_production_cattle_id ON milk_production (cattle_id);
